/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param current_service The service the user currently uses to login
 * @param new_service The service the user will use to login
 * @param email The email of the user
 * @param password The password used with the current service
 * @param mfa_code The MFA code of the current service
 * @param ldap_id The LDAP/AD id of the user
 */
data class Body_14 (
    /* The service the user currently uses to login */
    val current_service: kotlin.String,
    /* The service the user will use to login */
    val new_service: kotlin.String,
    /* The email of the user */
    val email: kotlin.String? = null,
    /* The password used with the current service */
    val password: kotlin.String? = null,
    /* The MFA code of the current service */
    val mfa_code: kotlin.String? = null,
    /* The LDAP/AD id of the user */
    val ldap_id: kotlin.String? = null
) {

}

