/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param id The channel's id, not updatable
 * @param name The unique handle for the channel, will be present in the channel URL
 * @param display_name The non-unique UI name for the channel
 * @param purpose A short description of the purpose of the channel
 * @param header Markdown-formatted text to display in the header of the channel
 * @param type 'O' for a public channel, 'P' for a private channel
 */
data class Body_23 (
    /* The channel's id, not updatable */
    val id: kotlin.String,
    /* The unique handle for the channel, will be present in the channel URL */
    val name: kotlin.String? = null,
    /* The non-unique UI name for the channel */
    val display_name: kotlin.String? = null,
    /* A short description of the purpose of the channel */
    val purpose: kotlin.String? = null,
    /* Markdown-formatted text to display in the header of the channel */
    val header: kotlin.String? = null,
    /* 'O' for a public channel, 'P' for a private channel */
    val type: kotlin.String? = null
) {

}

