/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param team_id Team ID to where the command should be created
 * @param method `'P'` for post request, `'G'` for get request
 * @param trigger Activation word to trigger the command
 * @param url The URL that the command will make the request
 */
data class Body_38 (
    /* Team ID to where the command should be created */
    val team_id: kotlin.String,
    /* `'P'` for post request, `'G'` for get request */
    val method: kotlin.String,
    /* Activation word to trigger the command */
    val trigger: kotlin.String,
    /* The URL that the command will make the request */
    val url: kotlin.String
) {

}

