/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param is_pinned Set to `true` to pin the post to the channel it is in
 * @param message The message text of the post
 * @param file_ids The list of files attached to this post
 * @param has_reactions Set to `true` if the post has reactions to it
 * @param props A general JSON property bag to attach to the post
 */
data class Body_28 (
    /* Set to `true` to pin the post to the channel it is in */
    val is_pinned: kotlin.Boolean? = null,
    /* The message text of the post */
    val message: kotlin.String? = null,
    /* The list of files attached to this post */
    val file_ids: kotlin.Array<kotlin.String>? = null,
    /* Set to `true` if the post has reactions to it */
    val has_reactions: kotlin.Boolean? = null,
    /* A general JSON property bag to attach to the post */
    val props: kotlin.String? = null
) {

}

