/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param hook_id Outgoing webhook GUID
 * @param channel_id The ID of a public channel or private group that receives the webhook payloads.
 * @param display_name The display name for this incoming webhook
 * @param description The description for this incoming webhook
 */
data class Body_37 (
    /* Outgoing webhook GUID */
    val hook_id: kotlin.String,
    /* The ID of a public channel or private group that receives the webhook payloads. */
    val channel_id: kotlin.String,
    /* The display name for this incoming webhook */
    val display_name: kotlin.String,
    /* The description for this incoming webhook */
    val description: kotlin.String
) {

}

