/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param user_id The ID of user to add into the channel
 * @param post_root_id The ID of root post where link to add channel member originates
 */
data class Body_26 (
    /* The ID of user to add into the channel */
    val user_id: kotlin.String,
    /* The ID of root post where link to add channel member originates */
    val post_root_id: kotlin.String? = null
) {

}

