/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param team_id The ID of the team that the webhook watchs
 * @param channel_id The ID of a public channel that the webhook watchs
 * @param description The description for this outgoing webhook
 * @param display_name The display name for this outgoing webhook
 * @param trigger_words List of words for the webhook to trigger on
 * @param trigger_when When to trigger the webhook, `0` when a trigger word is present at all and `1` if the message starts with a trigger word
 * @param callback_urls The URLs to POST the payloads to when the webhook is triggered
 * @param content_type The format to POST the data in, either `application/json` or `application/x-www-form-urlencoded`
 */
data class Body_36 (
    /* The ID of the team that the webhook watchs */
    val team_id: kotlin.String,
    /* The display name for this outgoing webhook */
    val display_name: kotlin.String,
    /* List of words for the webhook to trigger on */
    val trigger_words: kotlin.Array<kotlin.String>,
    /* The URLs to POST the payloads to when the webhook is triggered */
    val callback_urls: kotlin.Array<kotlin.String>,
    /* The ID of a public channel that the webhook watchs */
    val channel_id: kotlin.String? = null,
    /* The description for this outgoing webhook */
    val description: kotlin.String? = null,
    /* When to trigger the webhook, `0` when a trigger word is present at all and `1` if the message starts with a trigger word */
    val trigger_when: kotlin.Int? = null,
    /* The format to POST the data in, either `application/json` or `application/x-www-form-urlencoded` */
    val content_type: kotlin.String? = null
) {

}

