/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param name Unique handler for a team, will be present in the team URL
 * @param display_name Non-unique UI name for the team
 * @param type `'O'` for open, `'I'` for invite only
 */
data class Body_17 (
    /* Unique handler for a team, will be present in the team URL */
    val name: kotlin.String,
    /* Non-unique UI name for the team */
    val display_name: kotlin.String,
    /* `'O'` for open, `'I'` for invite only */
    val type: kotlin.String
) {

}

