/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param term The term to match against username, full name, nickname and email
 * @param team_id If provided, only search users on this team
 * @param not_in_team_id If provided, only search users not on this team
 * @param in_channel_id If provided, only search users in this channel
 * @param not_in_channel_id If provided, only search users not in this channel. Must specifiy `team_id` when using this option
 * @param allow_inactive When `true`, include deactivated users in the results
 * @param without_team Set this to `true` if you would like to search for users that are not on a team. This option takes precendence over `team_id`, `in_channel_id`, and `not_in_channel_id`.
 */
data class Body_1 (
    /* The term to match against username, full name, nickname and email */
    val term: kotlin.String,
    /* If provided, only search users on this team */
    val team_id: kotlin.String? = null,
    /* If provided, only search users not on this team */
    val not_in_team_id: kotlin.String? = null,
    /* If provided, only search users in this channel */
    val in_channel_id: kotlin.String? = null,
    /* If provided, only search users not in this channel. Must specifiy `team_id` when using this option */
    val not_in_channel_id: kotlin.String? = null,
    /* When `true`, include deactivated users in the results */
    val allow_inactive: kotlin.Boolean? = null,
    /* Set this to `true` if you would like to search for users that are not on a team. This option takes precendence over `team_id`, `in_channel_id`, and `not_in_channel_id`. */
    val without_team: kotlin.Boolean? = null
) {

}

