/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param create_at 
 * @param update_at 
 * @param delete_at 
 * @param team_id 
 * @param type 
 * @param display_name 
 * @param name 
 * @param header 
 * @param purpose 
 * @param last_post_at 
 * @param total_msg_count 
 * @param extra_update_at 
 * @param creator_id 
 */
data class Channel (
    val id: kotlin.String? = null,
    val create_at: kotlin.Int? = null,
    val update_at: kotlin.Int? = null,
    val delete_at: kotlin.Int? = null,
    val team_id: kotlin.String? = null,
    val type: kotlin.String? = null,
    val display_name: kotlin.String? = null,
    val name: kotlin.String? = null,
    val header: kotlin.String? = null,
    val purpose: kotlin.String? = null,
    val last_post_at: kotlin.Int? = null,
    val total_msg_count: kotlin.Int? = null,
    val extra_update_at: kotlin.Int? = null,
    val creator_id: kotlin.String? = null
) {

}

