/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.ChannelNotifyProps

/**
 * 
 * @param channel_id 
 * @param user_id 
 * @param roles 
 * @param last_viewed_at 
 * @param msg_count 
 * @param mention_count 
 * @param notify_props Field only visible to self and admins
 * @param last_update_at 
 */
data class ChannelMember (
    val channel_id: kotlin.String? = null,
    val user_id: kotlin.String? = null,
    val roles: kotlin.String? = null,
    val last_viewed_at: kotlin.Int? = null,
    val msg_count: kotlin.Int? = null,
    val mention_count: kotlin.Int? = null,
    /* Field only visible to self and admins */
    val notify_props: ChannelNotifyProps? = null,
    val last_update_at: kotlin.Int? = null
) {

}

