/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param id The ID of the slash command
 * @param token The token which is used to verify the source of the payload
 * @param create_at Timestamp when the command was created
 * @param updated_at Timestamp when the command was last updated
 * @param deleted_at Timestamp when the command was deleted, 0 if never deleted
 * @param creator_id The user id for the commands creator
 * @param team_id The team id for which this command is configured
 * @param trigger The string that triggers this command
 * @param method Is the trigger done with HTTP Get ('G') or HTTP Post ('P')
 * @param username What is the username for the response post
 * @param icon_url The url to find the icon for this users avatar
 * @param auto_complete Use auto complete for this command
 * @param auto_complete_desc The description for this command shown when selecting the command
 * @param auto_complete_hint The hint for this command
 * @param display_name Display name for the command
 * @param description Description for this command
 * @param url The URL that is triggered
 */
data class Command (
    /* The ID of the slash command */
    val id: kotlin.String? = null,
    /* The token which is used to verify the source of the payload */
    val token: kotlin.String? = null,
    /* Timestamp when the command was created */
    val create_at: kotlin.Int? = null,
    /* Timestamp when the command was last updated */
    val updated_at: kotlin.Int? = null,
    /* Timestamp when the command was deleted, 0 if never deleted */
    val deleted_at: kotlin.Int? = null,
    /* The user id for the commands creator */
    val creator_id: kotlin.String? = null,
    /* The team id for which this command is configured */
    val team_id: kotlin.String? = null,
    /* The string that triggers this command */
    val trigger: kotlin.String? = null,
    /* Is the trigger done with HTTP Get ('G') or HTTP Post ('P') */
    val method: kotlin.String? = null,
    /* What is the username for the response post */
    val username: kotlin.String? = null,
    /* The url to find the icon for this users avatar */
    val icon_url: kotlin.String? = null,
    /* Use auto complete for this command */
    val auto_complete: kotlin.Boolean? = null,
    /* The description for this command shown when selecting the command */
    val auto_complete_desc: kotlin.String? = null,
    /* The hint for this command */
    val auto_complete_hint: kotlin.String? = null,
    /* Display name for the command */
    val display_name: kotlin.String? = null,
    /* Description for this command */
    val description: kotlin.String? = null,
    /* The URL that is triggered */
    val url: kotlin.String? = null
) {

}

