/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param create_at 
 * @param user_id 
 * @param status 
 * @param count 
 * @param desc 
 * @param type 
 * @param start_at 
 * @param end_at 
 * @param keywords 
 * @param emails 
 */
data class Compliance (
    val id: kotlin.String? = null,
    val create_at: kotlin.Int? = null,
    val user_id: kotlin.String? = null,
    val status: kotlin.String? = null,
    val count: kotlin.Int? = null,
    val desc: kotlin.String? = null,
    val type: kotlin.String? = null,
    val start_at: kotlin.Int? = null,
    val end_at: kotlin.Int? = null,
    val keywords: kotlin.String? = null,
    val emails: kotlin.String? = null
) {

}

