/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param DriverName 
 * @param DataSource 
 * @param DataSourceReplicas 
 * @param MaxIdleConns 
 * @param MaxOpenConns 
 * @param Trace 
 * @param AtRestEncryptKey 
 */
data class Config_SqlSettings (
    val DriverName: kotlin.String? = null,
    val DataSource: kotlin.String? = null,
    val DataSourceReplicas: kotlin.Array<kotlin.String>? = null,
    val MaxIdleConns: kotlin.Int? = null,
    val MaxOpenConns: kotlin.Int? = null,
    val Trace: kotlin.Boolean? = null,
    val AtRestEncryptKey: kotlin.String? = null
) {

}

