/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param Enable 
 * @param Secret 
 * @param Id 
 * @param Scope 
 * @param AuthEndpoint 
 * @param TokenEndpoint 
 * @param UserApiEndpoint 
 */
data class Config_GitLabSettings (
    val Enable: kotlin.Boolean? = null,
    val Secret: kotlin.String? = null,
    val Id: kotlin.String? = null,
    val Scope: kotlin.String? = null,
    val AuthEndpoint: kotlin.String? = null,
    val TokenEndpoint: kotlin.String? = null,
    val UserApiEndpoint: kotlin.String? = null
) {

}

