/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param Enable 
 * @param Verify 
 * @param Encrypt 
 * @param IdpUrl 
 * @param IdpDescriptorUrl 
 * @param AssertionConsumerServiceURL 
 * @param IdpCertificateFile 
 * @param PublicCertificateFile 
 * @param PrivateKeyFile 
 * @param FirstNameAttribute 
 * @param LastNameAttribute 
 * @param EmailAttribute 
 * @param UsernameAttribute 
 * @param NicknameAttribute 
 * @param LocaleAttribute 
 * @param PositionAttribute 
 * @param LoginButtonText 
 */
data class Config_SamlSettings (
    val Enable: kotlin.Boolean? = null,
    val Verify: kotlin.Boolean? = null,
    val Encrypt: kotlin.Boolean? = null,
    val IdpUrl: kotlin.String? = null,
    val IdpDescriptorUrl: kotlin.String? = null,
    val AssertionConsumerServiceURL: kotlin.String? = null,
    val IdpCertificateFile: kotlin.String? = null,
    val PublicCertificateFile: kotlin.String? = null,
    val PrivateKeyFile: kotlin.String? = null,
    val FirstNameAttribute: kotlin.String? = null,
    val LastNameAttribute: kotlin.String? = null,
    val EmailAttribute: kotlin.String? = null,
    val UsernameAttribute: kotlin.String? = null,
    val NicknameAttribute: kotlin.String? = null,
    val LocaleAttribute: kotlin.String? = null,
    val PositionAttribute: kotlin.String? = null,
    val LoginButtonText: kotlin.String? = null
) {

}

