/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.Config_AnalyticsSettings
import io.swagger.client.models.Config_ClusterSettings
import io.swagger.client.models.Config_ComplianceSettings
import io.swagger.client.models.Config_EmailSettings
import io.swagger.client.models.Config_FileSettings
import io.swagger.client.models.Config_GitLabSettings
import io.swagger.client.models.Config_LdapSettings
import io.swagger.client.models.Config_LocalizationSettings
import io.swagger.client.models.Config_LogSettings
import io.swagger.client.models.Config_MetricsSettings
import io.swagger.client.models.Config_NativeAppSettings
import io.swagger.client.models.Config_PasswordSettings
import io.swagger.client.models.Config_PrivacySettings
import io.swagger.client.models.Config_RateLimitSettings
import io.swagger.client.models.Config_SamlSettings
import io.swagger.client.models.Config_ServiceSettings
import io.swagger.client.models.Config_SqlSettings
import io.swagger.client.models.Config_SupportSettings
import io.swagger.client.models.Config_TeamSettings
import io.swagger.client.models.Config_WebrtcSettings

/**
 * 
 * @param ServiceSettings 
 * @param TeamSettings 
 * @param SqlSettings 
 * @param LogSettings 
 * @param PasswordSettings 
 * @param FileSettings 
 * @param EmailSettings 
 * @param RateLimitSettings 
 * @param PrivacySettings 
 * @param SupportSettings 
 * @param GitLabSettings 
 * @param GoogleSettings 
 * @param Office365Settings 
 * @param LdapSettings 
 * @param ComplianceSettings 
 * @param LocalizationSettings 
 * @param SamlSettings 
 * @param NativeAppSettings 
 * @param ClusterSettings 
 * @param MetricsSettings 
 * @param AnalyticsSettings 
 * @param WebrtcSettings 
 */
data class Config (
    val ServiceSettings: Config_ServiceSettings? = null,
    val TeamSettings: Config_TeamSettings? = null,
    val SqlSettings: Config_SqlSettings? = null,
    val LogSettings: Config_LogSettings? = null,
    val PasswordSettings: Config_PasswordSettings? = null,
    val FileSettings: Config_FileSettings? = null,
    val EmailSettings: Config_EmailSettings? = null,
    val RateLimitSettings: Config_RateLimitSettings? = null,
    val PrivacySettings: Config_PrivacySettings? = null,
    val SupportSettings: Config_SupportSettings? = null,
    val GitLabSettings: Config_GitLabSettings? = null,
    val GoogleSettings: Config_GitLabSettings? = null,
    val Office365Settings: Config_GitLabSettings? = null,
    val LdapSettings: Config_LdapSettings? = null,
    val ComplianceSettings: Config_ComplianceSettings? = null,
    val LocalizationSettings: Config_LocalizationSettings? = null,
    val SamlSettings: Config_SamlSettings? = null,
    val NativeAppSettings: Config_NativeAppSettings? = null,
    val ClusterSettings: Config_ClusterSettings? = null,
    val MetricsSettings: Config_MetricsSettings? = null,
    val AnalyticsSettings: Config_AnalyticsSettings? = null,
    val WebrtcSettings: Config_WebrtcSettings? = null
) {

}

