/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param Enable 
 * @param LdapServer 
 * @param LdapPort 
 * @param ConnectionSecurity 
 * @param BaseDN 
 * @param BindUsername 
 * @param BindPassword 
 * @param UserFilter 
 * @param FirstNameAttribute 
 * @param LastNameAttribute 
 * @param EmailAttribute 
 * @param UsernameAttribute 
 * @param NicknameAttribute 
 * @param IdAttribute 
 * @param PositionAttribute 
 * @param SyncIntervalMinutes 
 * @param SkipCertificateVerification 
 * @param QueryTimeout 
 * @param MaxPageSize 
 * @param LoginFieldName 
 */
data class Config_LdapSettings (
    val Enable: kotlin.Boolean? = null,
    val LdapServer: kotlin.String? = null,
    val LdapPort: kotlin.Int? = null,
    val ConnectionSecurity: kotlin.String? = null,
    val BaseDN: kotlin.String? = null,
    val BindUsername: kotlin.String? = null,
    val BindPassword: kotlin.String? = null,
    val UserFilter: kotlin.String? = null,
    val FirstNameAttribute: kotlin.String? = null,
    val LastNameAttribute: kotlin.String? = null,
    val EmailAttribute: kotlin.String? = null,
    val UsernameAttribute: kotlin.String? = null,
    val NicknameAttribute: kotlin.String? = null,
    val IdAttribute: kotlin.String? = null,
    val PositionAttribute: kotlin.String? = null,
    val SyncIntervalMinutes: kotlin.Int? = null,
    val SkipCertificateVerification: kotlin.Boolean? = null,
    val QueryTimeout: kotlin.Int? = null,
    val MaxPageSize: kotlin.Int? = null,
    val LoginFieldName: kotlin.String? = null
) {

}

