/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param EnableConsole 
 * @param ConsoleLevel 
 * @param EnableFile 
 * @param FileLevel 
 * @param FileFormat 
 * @param FileLocation 
 * @param EnableWebhookDebugging 
 * @param EnableDiagnostics 
 */
data class Config_LogSettings (
    val EnableConsole: kotlin.Boolean? = null,
    val ConsoleLevel: kotlin.String? = null,
    val EnableFile: kotlin.Boolean? = null,
    val FileLevel: kotlin.String? = null,
    val FileFormat: kotlin.String? = null,
    val FileLocation: kotlin.String? = null,
    val EnableWebhookDebugging: kotlin.Boolean? = null,
    val EnableDiagnostics: kotlin.Boolean? = null
) {

}

