/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param SiteURL 
 * @param ListenAddress 
 * @param ConnectionSecurity 
 * @param TLSCertFile 
 * @param TLSKeyFile 
 * @param UseLetsEncrypt 
 * @param LetsEncryptCertificateCacheFile 
 * @param Forward80To443 
 * @param ReadTimeout 
 * @param WriteTimeout 
 * @param MaximumLoginAttempts 
 * @param SegmentDeveloperKey 
 * @param GoogleDeveloperKey 
 * @param EnableOAuthServiceProvider 
 * @param EnableIncomingWebhooks 
 * @param EnableOutgoingWebhooks 
 * @param EnableCommands 
 * @param EnableOnlyAdminIntegrations 
 * @param EnablePostUsernameOverride 
 * @param EnablePostIconOverride 
 * @param EnableTesting 
 * @param EnableDeveloper 
 * @param EnableSecurityFixAlert 
 * @param EnableInsecureOutgoingConnections 
 * @param EnableMultifactorAuthentication 
 * @param EnforceMultifactorAuthentication 
 * @param AllowCorsFrom 
 * @param SessionLengthWebInDays 
 * @param SessionLengthMobileInDays 
 * @param SessionLengthSSOInDays 
 * @param SessionCacheInMinutes 
 * @param WebsocketSecurePort 
 * @param WebsocketPort 
 * @param WebserverMode 
 * @param EnableCustomEmoji 
 * @param RestrictCustomEmojiCreation 
 */
data class Config_ServiceSettings (
    val SiteURL: kotlin.String? = null,
    val ListenAddress: kotlin.String? = null,
    val ConnectionSecurity: kotlin.String? = null,
    val TLSCertFile: kotlin.String? = null,
    val TLSKeyFile: kotlin.String? = null,
    val UseLetsEncrypt: kotlin.Boolean? = null,
    val LetsEncryptCertificateCacheFile: kotlin.String? = null,
    val Forward80To443: kotlin.Boolean? = null,
    val ReadTimeout: kotlin.Int? = null,
    val WriteTimeout: kotlin.Int? = null,
    val MaximumLoginAttempts: kotlin.Int? = null,
    val SegmentDeveloperKey: kotlin.String? = null,
    val GoogleDeveloperKey: kotlin.String? = null,
    val EnableOAuthServiceProvider: kotlin.Boolean? = null,
    val EnableIncomingWebhooks: kotlin.Boolean? = null,
    val EnableOutgoingWebhooks: kotlin.Boolean? = null,
    val EnableCommands: kotlin.Boolean? = null,
    val EnableOnlyAdminIntegrations: kotlin.Boolean? = null,
    val EnablePostUsernameOverride: kotlin.Boolean? = null,
    val EnablePostIconOverride: kotlin.Boolean? = null,
    val EnableTesting: kotlin.Boolean? = null,
    val EnableDeveloper: kotlin.Boolean? = null,
    val EnableSecurityFixAlert: kotlin.Boolean? = null,
    val EnableInsecureOutgoingConnections: kotlin.Boolean? = null,
    val EnableMultifactorAuthentication: kotlin.Boolean? = null,
    val EnforceMultifactorAuthentication: kotlin.Boolean? = null,
    val AllowCorsFrom: kotlin.String? = null,
    val SessionLengthWebInDays: kotlin.Int? = null,
    val SessionLengthMobileInDays: kotlin.Int? = null,
    val SessionLengthSSOInDays: kotlin.Int? = null,
    val SessionCacheInMinutes: kotlin.Int? = null,
    val WebsocketSecurePort: kotlin.Int? = null,
    val WebsocketPort: kotlin.Int? = null,
    val WebserverMode: kotlin.String? = null,
    val EnableCustomEmoji: kotlin.Boolean? = null,
    val RestrictCustomEmojiCreation: kotlin.String? = null
) {

}

