/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param MaxFileSize 
 * @param DriverName 
 * @param Directory 
 * @param EnablePublicLink 
 * @param PublicLinkSalt 
 * @param ThumbnailWidth 
 * @param ThumbnailHeight 
 * @param PreviewWidth 
 * @param PreviewHeight 
 * @param ProfileWidth 
 * @param ProfileHeight 
 * @param InitialFont 
 * @param AmazonS3AccessKeyId 
 * @param AmazonS3SecretAccessKey 
 * @param AmazonS3Bucket 
 * @param AmazonS3Region 
 * @param AmazonS3Endpoint 
 * @param AmazonS3SSL 
 */
data class Config_FileSettings (
    val MaxFileSize: kotlin.Int? = null,
    val DriverName: kotlin.String? = null,
    val Directory: kotlin.String? = null,
    val EnablePublicLink: kotlin.Boolean? = null,
    val PublicLinkSalt: kotlin.String? = null,
    val ThumbnailWidth: kotlin.Int? = null,
    val ThumbnailHeight: kotlin.Int? = null,
    val PreviewWidth: kotlin.Int? = null,
    val PreviewHeight: kotlin.Int? = null,
    val ProfileWidth: kotlin.Int? = null,
    val ProfileHeight: kotlin.Int? = null,
    val InitialFont: kotlin.String? = null,
    val AmazonS3AccessKeyId: kotlin.String? = null,
    val AmazonS3SecretAccessKey: kotlin.String? = null,
    val AmazonS3Bucket: kotlin.String? = null,
    val AmazonS3Region: kotlin.String? = null,
    val AmazonS3Endpoint: kotlin.String? = null,
    val AmazonS3SSL: kotlin.Boolean? = null
) {

}

