/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param message_deletion_enabled Indicates whether data retention policy deletion of messages is enabled.
 * @param file_deletion_enabled Indicates whether data retention policy deletion of file attachments is enabled.
 * @param message_retention_cutoff The current server timestamp before which messages should be deleted.
 * @param file_retention_cutoff The current server timestamp before which files should be deleted.
 */
data class DataRetentionPolicy (
    /* Indicates whether data retention policy deletion of messages is enabled. */
    val message_deletion_enabled: kotlin.Boolean? = null,
    /* Indicates whether data retention policy deletion of file attachments is enabled. */
    val file_deletion_enabled: kotlin.Boolean? = null,
    /* The current server timestamp before which messages should be deleted. */
    val message_retention_cutoff: kotlin.Int? = null,
    /* The current server timestamp before which files should be deleted. */
    val file_retention_cutoff: kotlin.Int? = null
) {

}

