/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param id The unique identifier for this file
 * @param user_id The ID of the user that uploaded this file
 * @param post_id If this file is attached to a post, the ID of that post
 * @param create_at 
 * @param update_at 
 * @param delete_at 
 * @param name The name of the file
 * @param extension The extension at the end of the file name
 * @param size The size of the file in bytes
 * @param mime_type The MIME type of the file
 * @param width If this file is an image, the width of the file
 * @param height If this file is an image, the height of the file
 * @param has_preview_image If this file is an image, whether or not it has a preview-sized version
 */
data class FileInfo (
    /* The unique identifier for this file */
    val id: kotlin.String? = null,
    /* The ID of the user that uploaded this file */
    val user_id: kotlin.String? = null,
    /* If this file is attached to a post, the ID of that post */
    val post_id: kotlin.String? = null,
    val create_at: kotlin.Int? = null,
    val update_at: kotlin.Int? = null,
    val delete_at: kotlin.Int? = null,
    /* The name of the file */
    val name: kotlin.String? = null,
    /* The extension at the end of the file name */
    val extension: kotlin.String? = null,
    /* The size of the file in bytes */
    val size: kotlin.Int? = null,
    /* The MIME type of the file */
    val mime_type: kotlin.String? = null,
    /* If this file is an image, the width of the file */
    val width: kotlin.Int? = null,
    /* If this file is an image, the height of the file */
    val height: kotlin.Int? = null,
    /* If this file is an image, whether or not it has a preview-sized version */
    val has_preview_image: kotlin.Boolean? = null
) {

}

