/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param follow_link The link for the user to follow to login or to complete the account switching when the current service is OAuth2/SAML
 */
data class Inline_response_200_2 (
    /* The link for the user to follow to login or to complete the account switching when the current service is OAuth2/SAML */
    val follow_link: kotlin.String? = null
) {

}

