/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.FileInfo

/**
 * 
 * @param file_infos A list of file metadata that has been stored in the database
 * @param client_ids A list of the client_ids that were provided in the request
 */
data class Inline_response_200_6 (
    /* A list of file metadata that has been stored in the database */
    val file_infos: kotlin.Array<FileInfo>? = null,
    /* A list of the client_ids that were provided in the request */
    val client_ids: kotlin.Array<kotlin.String>? = null
) {

}

