/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param status Value should be \"OK\" if successful
 * @param last_viewed_at_times A JSON object mapping channel IDs to the channel view times
 */
data class Inline_response_200_5 (
    /* Value should be \"OK\" if successful */
    val status: kotlin.String? = null,
    /* A JSON object mapping channel IDs to the channel view times */
    val last_viewed_at_times: kotlin.Any? = null
) {

}

