/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param id The client id of the application
 * @param client_secret The client secret of the application
 * @param name The name of the client application
 * @param description A short description of the application
 * @param icon_url A URL to an icon to display with the application
 * @param callback_urls A list of callback URLs for the appliation
 * @param homepage A link to the website of the application
 * @param is_trusted Set this to `true` to skip asking users for permission
 * @param create_at The time of registration for the application
 * @param update_at The last time of update for the application
 */
data class OAuthApp (
    /* The client id of the application */
    val id: kotlin.String? = null,
    /* The client secret of the application */
    val client_secret: kotlin.String? = null,
    /* The name of the client application */
    val name: kotlin.String? = null,
    /* A short description of the application */
    val description: kotlin.String? = null,
    /* A URL to an icon to display with the application */
    val icon_url: kotlin.String? = null,
    /* A list of callback URLs for the appliation */
    val callback_urls: kotlin.Array<kotlin.String>? = null,
    /* A link to the website of the application */
    val homepage: kotlin.String? = null,
    /* Set this to `true` to skip asking users for permission */
    val is_trusted: kotlin.Boolean? = null,
    /* The time of registration for the application */
    val create_at: kotlin.Int? = null,
    /* The last time of update for the application */
    val update_at: kotlin.Int? = null
) {

}

