/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.PluginManifest_webapp

/**
 * 
 * @param id Globally unique identifier that represents the plugin.
 * @param version Version number of the plugin.
 * @param webapp 
 */
data class PluginManifestWebapp (
    /* Globally unique identifier that represents the plugin. */
    val id: kotlin.String? = null,
    /* Version number of the plugin. */
    val version: kotlin.String? = null,
    val webapp: PluginManifest_webapp? = null
) {

}

