/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param channel_id The channel ID to post in
 * @param message The message contents, can be formatted with Markdown
 * @param root_id The post ID to comment on
 * @param file_ids A list of file IDs to associate with the post
 * @param props A general JSON property bag to attach to the post
 */
data class Post (
    /* The channel ID to post in */
    val channel_id: kotlin.String,
    /* The message contents, can be formatted with Markdown */
    val message: kotlin.String,
    /* The post ID to comment on */
    val root_id: kotlin.String? = null,
    /* A list of file IDs to associate with the post */
    val file_ids: kotlin.Array<kotlin.String>? = null,
    /* A general JSON property bag to attach to the post */
    val props: kotlin.String? = null
) {

}

