/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param user_id The ID of the user that made this reaction
 * @param post_id The ID of the post to which this reaction was made
 * @param emoji_name The name of the emoji that was used for this reaction
 * @param create_at The time at which this reaction was made
 */
data class Reaction (
    /* The ID of the user that made this reaction */
    val user_id: kotlin.String? = null,
    /* The ID of the post to which this reaction was made */
    val post_id: kotlin.String? = null,
    /* The name of the emoji that was used for this reaction */
    val emoji_name: kotlin.String? = null,
    /* The time at which this reaction was made */
    val create_at: kotlin.Int? = null
) {

}

