/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param idp_certificate_file Status is good when `true`
 * @param public_certificate_file Status is good when `true`
 * @param private_key_file Status is good when `true`
 */
data class SamlCertificateStatus (
    /* Status is good when `true` */
    val idp_certificate_file: kotlin.Boolean? = null,
    /* Status is good when `true` */
    val public_certificate_file: kotlin.Boolean? = null,
    /* Status is good when `true` */
    val private_key_file: kotlin.Boolean? = null
) {

}

