/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.TeamMember

/**
 * 
 * @param create_at 
 * @param device_id 
 * @param expires_at 
 * @param id 
 * @param is_oauth 
 * @param last_activity_at 
 * @param props 
 * @param roles 
 * @param team_members 
 * @param token 
 * @param user_id 
 */
data class Session (
    val create_at: kotlin.Int? = null,
    val device_id: kotlin.String? = null,
    val expires_at: kotlin.Int? = null,
    val id: kotlin.String? = null,
    val is_oauth: kotlin.Boolean? = null,
    val last_activity_at: kotlin.Int? = null,
    val props: kotlin.Any? = null,
    val roles: kotlin.String? = null,
    val team_members: kotlin.Array<TeamMember>? = null,
    val token: kotlin.String? = null,
    val user_id: kotlin.String? = null
) {

}

