/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.SlackAttachmentField

/**
 * 
 * @param Id 
 * @param Fallback 
 * @param Color 
 * @param Pretext 
 * @param AuthorName 
 * @param AuthorLink 
 * @param AuthorIcon 
 * @param Title 
 * @param TitleLink 
 * @param Text 
 * @param Fields 
 * @param ImageURL 
 * @param ThumbURL 
 * @param Footer 
 * @param FooterIcon 
 * @param Timestamp The timestamp of the slack attahment, either type of string or integer
 */
data class SlackAttachment (
    val Id: kotlin.String? = null,
    val Fallback: kotlin.String? = null,
    val Color: kotlin.String? = null,
    val Pretext: kotlin.String? = null,
    val AuthorName: kotlin.String? = null,
    val AuthorLink: kotlin.String? = null,
    val AuthorIcon: kotlin.String? = null,
    val Title: kotlin.String? = null,
    val TitleLink: kotlin.String? = null,
    val Text: kotlin.String? = null,
    val Fields: kotlin.Array<SlackAttachmentField>? = null,
    val ImageURL: kotlin.String? = null,
    val ThumbURL: kotlin.String? = null,
    val Footer: kotlin.String? = null,
    val FooterIcon: kotlin.String? = null,
    /* The timestamp of the slack attahment, either type of string or integer */
    val Timestamp: kotlin.String? = null
) {

}

