/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param email Set to \"true\" to enable email notifications, \"false\" to disable. Defaults to \"true\".
 * @param push Set to \"all\" to receive push notifications for all activity, \"mention\" for mentions and direct messages only, and \"none\" to disable. Defaults to \"mention\".
 * @param desktop Set to \"all\" to receive desktop notifications for all activity, \"mention\" for mentions and direct messages only, and \"none\" to disable. Defaults to \"all\".
 * @param desktop_sound Set to \"true\" to enable sound on desktop notifications, \"false\" to disable. Defaults to \"true\".
 * @param mention_keys A comma-separated list of words to count as mentions. Defaults to username and @username.
 * @param channel Set to \"true\" to enable channel-wide notifications (@channel, @all, etc.), \"false\" to disable. Defaults to \"true\".
 * @param first_name Set to \"true\" to enable mentions for first name. Defaults to \"true\" if a first name is set, \"false\" otherwise.
 */
data class UserNotifyProps (
    /* Set to \"true\" to enable email notifications, \"false\" to disable. Defaults to \"true\". */
    val email: kotlin.String? = null,
    /* Set to \"all\" to receive push notifications for all activity, \"mention\" for mentions and direct messages only, and \"none\" to disable. Defaults to \"mention\". */
    val push: kotlin.String? = null,
    /* Set to \"all\" to receive desktop notifications for all activity, \"mention\" for mentions and direct messages only, and \"none\" to disable. Defaults to \"all\". */
    val desktop: kotlin.String? = null,
    /* Set to \"true\" to enable sound on desktop notifications, \"false\" to disable. Defaults to \"true\". */
    val desktop_sound: kotlin.String? = null,
    /* A comma-separated list of words to count as mentions. Defaults to username and @username. */
    val mention_keys: kotlin.String? = null,
    /* Set to \"true\" to enable channel-wide notifications (@channel, @all, etc.), \"false\" to disable. Defaults to \"true\". */
    val channel: kotlin.String? = null,
    /* Set to \"true\" to enable mentions for first name. Defaults to \"true\" if a first name is set, \"false\" otherwise. */
    val first_name: kotlin.String? = null
) {

}

