/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.User

/**
 * 
 * @param in_channel A list of user objects in the channel
 * @param out_of_channel A list of user objects not in the channel
 */
data class UserAutocompleteInChannel (
    /* A list of user objects in the channel */
    val in_channel: kotlin.Array<User>? = null,
    /* A list of user objects not in the channel */
    val out_of_channel: kotlin.Array<User>? = null
) {

}

