/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.User

/**
 * 
 * @param users A list of users that are the main result of the query
 * @param out_of_channel A special case list of users returned when autocompleting in a specific channel. Omitted when empty or not relevant
 */
data class UserAutocomplete (
    /* A list of users that are the main result of the query */
    val users: kotlin.Array<User>? = null,
    /* A special case list of users returned when autocompleting in a specific channel. Omitted when empty or not relevant */
    val out_of_channel: kotlin.Array<User>? = null
) {

}

