/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.UserNotifyProps

/**
 * 
 * @param id 
 * @param create_at 
 * @param update_at 
 * @param delete_at 
 * @param username 
 * @param first_name 
 * @param last_name 
 * @param nickname 
 * @param email 
 * @param email_verified 
 * @param auth_service 
 * @param roles 
 * @param locale 
 * @param notify_props Field only visible to self and admins
 * @param props 
 * @param last_password_update 
 * @param last_picture_update 
 * @param failed_attempts 
 * @param mfa_active 
 */
data class User (
    val id: kotlin.String? = null,
    val create_at: kotlin.Int? = null,
    val update_at: kotlin.Int? = null,
    val delete_at: kotlin.Int? = null,
    val username: kotlin.String? = null,
    val first_name: kotlin.String? = null,
    val last_name: kotlin.String? = null,
    val nickname: kotlin.String? = null,
    val email: kotlin.String? = null,
    val email_verified: kotlin.Boolean? = null,
    val auth_service: kotlin.String? = null,
    val roles: kotlin.String? = null,
    val locale: kotlin.String? = null,
    /* Field only visible to self and admins */
    val notify_props: UserNotifyProps? = null,
    val props: kotlin.Any? = null,
    val last_password_update: kotlin.Int? = null,
    val last_picture_update: kotlin.Int? = null,
    val failed_attempts: kotlin.Int? = null,
    val mfa_active: kotlin.Boolean? = null
) {

}

