/**
* Mattermost API Reference
* ### API version 4 is stable with the Mattermost server 4.0 release. API version 3 is scheduled for deprecation on January 16th, 2018. [Details here](/#tag/APIv3-Deprecation). Looking for the APIv3 reference? It has moved [here](https://api.mattermost.com/v3). 
*
* OpenAPI spec version: 4.0.0
* Contact: feedback@mattermost.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param id Unique identifier for the token
 * @param token The token used for authentication
 * @param user_id The user the token authenticates for
 * @param description A description of the token usage
 */
data class UserAccessToken (
    /* Unique identifier for the token */
    val id: kotlin.String? = null,
    /* The token used for authentication */
    val token: kotlin.String? = null,
    /* The user the token authenticates for */
    val user_id: kotlin.String? = null,
    /* A description of the token usage */
    val description: kotlin.String? = null
) {

}

